spring:
  application:
    name: HopitalManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/HospitalDB
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 449173889065-m0ja9nflfoeh7rdskcf8oeaovpis7ki8.apps.googleusercontent.com
            client-secret: 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


server:
  servlet:
    context-path: /api

jwt:
  secretKey: 678nk2@2gkkkffmmmkkfkk&ëeeeeę)(*mfkjkabdkajewkfbaebfljefjbajebfb
